version: '3'

services:
  task-manager-db:
    image: postgres:latest
    container_name: task-manager-db
    restart: always
    tty: true
    volumes:
      - .volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    env_file:
      - .env

